authors:
  sebastjan:
    name: Sebastjan Cizel
    description: Research scientist specializing in machine learning and mathematical physics
    avatar: https://github.com/sebastjancizel.png
    url: https://sebastjancizel.github.io
